// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.240000,HLS_SYN_LAT=133,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=279,HLS_SYN_LUT=439,HLS_VERSION=2024_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10_fu_247_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter6_reg;
reg    ap_loop_exit_ready_delayed;
reg   [0:0] icmp_ln127_reg_127;
wire   [0:0] and_ln10_fu_195_p2;
reg   [0:0] and_ln10_reg_467;
wire   [0:0] empty_4_fu_201_p2;
reg   [0:0] empty_4_reg_472;
reg   [0:0] empty_4_reg_472_pp0_iter2_reg;
reg   [0:0] empty_4_reg_472_pp0_iter3_reg;
reg   [0:0] empty_4_reg_472_pp0_iter4_reg;
reg   [0:0] empty_4_reg_472_pp0_iter5_reg;
wire   [2:0] k_mid2_fu_207_p3;
reg   [2:0] k_mid2_reg_477;
reg   [2:0] k_mid2_reg_477_pp0_iter2_reg;
wire   [2:0] k_fu_215_p2;
reg   [2:0] k_reg_484;
wire   [0:0] icmp_ln12_fu_241_p2;
reg   [0:0] icmp_ln12_reg_490;
reg   [0:0] icmp_ln10_reg_495;
wire   [2:0] j_fu_297_p3;
reg   [2:0] j_reg_499;
wire   [4:0] add_ln12_2_fu_316_p2;
reg   [4:0] add_ln12_2_reg_504;
wire   [0:0] icmp_ln15_fu_322_p2;
reg   [0:0] icmp_ln15_reg_510;
reg   [0:0] icmp_ln15_reg_510_pp0_iter3_reg;
reg   [0:0] icmp_ln15_reg_510_pp0_iter4_reg;
reg   [0:0] icmp_ln15_reg_510_pp0_iter5_reg;
reg   [0:0] icmp_ln15_reg_510_pp0_iter6_reg;
wire   [4:0] add_ln16_1_fu_344_p2;
reg   [4:0] add_ln16_1_reg_515;
reg   [4:0] add_ln16_1_reg_515_pp0_iter4_reg;
reg   [4:0] add_ln16_1_reg_515_pp0_iter5_reg;
reg   [4:0] add_ln16_1_reg_515_pp0_iter6_reg;
reg   [0:0] ap_phi_mux_icmp_ln127_phi_fu_131_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln156_phi_fu_143_p4;
wire   [63:0] zext_ln16_4_fu_360_p1;
wire   [63:0] zext_ln16_5_fu_384_p1;
wire   [63:0] zext_ln16_1_fu_407_p1;
reg   [6:0] indvar_flatten131_fu_64;
wire   [6:0] add_ln10_1_fu_221_p2;
reg   [2:0] i2_fu_68;
wire   [2:0] i_fu_283_p3;
reg   [5:0] indvar_flatten3_fu_72;
wire   [5:0] select_ln12_1_fu_233_p3;
reg   [2:0] j4_fu_76;
reg   [2:0] k5_fu_80;
reg   [2:0] ap_sig_allocacmp_k5_load;
reg   [15:0] empty_fu_84;
wire   [15:0] grp_fu_415_p3;
reg   [15:0] ap_sig_allocacmp_p_load;
reg    a_ce0_local;
reg    b_ce0_local;
reg    prod_we0_local;
reg    prod_ce0_local;
wire   [0:0] xor_ln10_fu_189_p2;
wire   [5:0] add_ln12_1_fu_227_p2;
wire   [2:0] add_ln10_fu_269_p2;
wire   [2:0] select_ln10_fu_275_p3;
wire   [2:0] add_ln12_fu_291_p2;
wire   [4:0] tmp_fu_308_p3;
wire   [4:0] zext_ln12_fu_304_p1;
wire   [4:0] zext_ln16_fu_341_p1;
wire   [4:0] zext_ln16_3_fu_352_p1;
wire   [4:0] add_ln16_2_fu_355_p2;
wire   [4:0] tmp_1_fu_365_p3;
wire   [4:0] zext_ln16_2_fu_349_p1;
wire   [4:0] add_ln16_4_fu_372_p2;
wire   [4:0] add_ln16_3_fu_378_p2;
wire   [15:0] grp_fu_415_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_199;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 indvar_flatten131_fu_64 = 7'd0;
#0 i2_fu_68 = 3'd0;
#0 indvar_flatten3_fu_72 = 6'd0;
#0 j4_fu_76 = 3'd0;
#0 k5_fu_80 = 3'd0;
#0 empty_fu_84 = 16'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(a_q0),
    .din2(grp_fu_415_p2),
    .ce(1'b1),
    .dout(grp_fu_415_p3)
);

matrix_mult_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_199)) begin
            empty_fu_84 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            empty_fu_84 <= grp_fu_415_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_199)) begin
            i2_fu_68 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i2_fu_68 <= i_fu_283_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln10_reg_495 == 1'd0))) begin
        icmp_ln127_reg_127 <= icmp_ln12_reg_490;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        icmp_ln127_reg_127 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            indvar_flatten131_fu_64 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten131_fu_64 <= add_ln10_1_fu_221_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            indvar_flatten3_fu_72 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten3_fu_72 <= select_ln12_1_fu_233_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_199)) begin
            j4_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j4_fu_76 <= j_fu_297_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_199)) begin
            k5_fu_80 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            k5_fu_80 <= k_reg_484;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln12_2_reg_504 <= add_ln12_2_fu_316_p2;
        add_ln16_1_reg_515 <= add_ln16_1_fu_344_p2;
        add_ln16_1_reg_515_pp0_iter4_reg <= add_ln16_1_reg_515;
        add_ln16_1_reg_515_pp0_iter5_reg <= add_ln16_1_reg_515_pp0_iter4_reg;
        add_ln16_1_reg_515_pp0_iter6_reg <= add_ln16_1_reg_515_pp0_iter5_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter6_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        empty_4_reg_472_pp0_iter2_reg <= empty_4_reg_472;
        empty_4_reg_472_pp0_iter3_reg <= empty_4_reg_472_pp0_iter2_reg;
        empty_4_reg_472_pp0_iter4_reg <= empty_4_reg_472_pp0_iter3_reg;
        empty_4_reg_472_pp0_iter5_reg <= empty_4_reg_472_pp0_iter4_reg;
        icmp_ln15_reg_510_pp0_iter3_reg <= icmp_ln15_reg_510;
        icmp_ln15_reg_510_pp0_iter4_reg <= icmp_ln15_reg_510_pp0_iter3_reg;
        icmp_ln15_reg_510_pp0_iter5_reg <= icmp_ln15_reg_510_pp0_iter4_reg;
        icmp_ln15_reg_510_pp0_iter6_reg <= icmp_ln15_reg_510_pp0_iter5_reg;
        j_reg_499 <= j_fu_297_p3;
        k_mid2_reg_477_pp0_iter2_reg <= k_mid2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln10_reg_467 <= and_ln10_fu_195_p2;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter1_stage0;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        empty_4_reg_472 <= empty_4_fu_201_p2;
        icmp_ln10_reg_495 <= icmp_ln10_fu_247_p2;
        k_mid2_reg_477 <= k_mid2_fu_207_p3;
        k_reg_484 <= k_fu_215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln12_reg_490 <= icmp_ln12_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        icmp_ln15_reg_510 <= icmp_ln15_fu_322_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_247_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter1_stage0_pp0_iter6_reg))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln10_reg_495 == 1'd0))) begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = icmp_ln12_reg_490;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = icmp_ln12_reg_490;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln10_reg_495 == 1'd0))) begin
        ap_phi_mux_icmp_ln156_phi_fu_143_p4 = icmp_ln15_fu_322_p2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln156_phi_fu_143_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln156_phi_fu_143_p4 = icmp_ln15_fu_322_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_k5_load = k_reg_484;
    end else begin
        ap_sig_allocacmp_k5_load = k5_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_p_load = grp_fu_415_p3;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln15_reg_510_pp0_iter6_reg == 1'd1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln16_4_fu_360_p1;

assign a_ce0 = a_ce0_local;

assign add_ln10_1_fu_221_p2 = (indvar_flatten131_fu_64 + 7'd1);

assign add_ln10_fu_269_p2 = (i2_fu_68 + 3'd1);

assign add_ln12_1_fu_227_p2 = (indvar_flatten3_fu_72 + 6'd1);

assign add_ln12_2_fu_316_p2 = (tmp_fu_308_p3 + zext_ln12_fu_304_p1);

assign add_ln12_fu_291_p2 = (select_ln10_fu_275_p3 + 3'd1);

assign add_ln16_1_fu_344_p2 = (add_ln12_2_reg_504 + zext_ln16_fu_341_p1);

assign add_ln16_2_fu_355_p2 = (add_ln12_2_reg_504 + zext_ln16_3_fu_352_p1);

assign add_ln16_3_fu_378_p2 = (add_ln16_4_fu_372_p2 + zext_ln16_fu_341_p1);

assign add_ln16_4_fu_372_p2 = (tmp_1_fu_365_p3 + zext_ln16_2_fu_349_p1);

assign and_ln10_fu_195_p2 = (xor_ln10_fu_189_p2 & ap_phi_mux_icmp_ln156_phi_fu_143_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_199 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b_address0 = zext_ln16_5_fu_384_p1;

assign b_ce0 = b_ce0_local;

assign empty_4_fu_201_p2 = (ap_phi_mux_icmp_ln127_phi_fu_131_p4 | and_ln10_fu_195_p2);

assign grp_fu_415_p2 = ((empty_4_reg_472_pp0_iter5_reg[0:0] == 1'b1) ? 16'd0 : ap_sig_allocacmp_p_load);

assign i_fu_283_p3 = ((icmp_ln127_reg_127[0:0] == 1'b1) ? add_ln10_fu_269_p2 : i2_fu_68);

assign icmp_ln10_fu_247_p2 = ((indvar_flatten131_fu_64 == 7'd124) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_241_p2 = ((select_ln12_1_fu_233_p3 == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_322_p2 = ((k_reg_484 == 3'd5) ? 1'b1 : 1'b0);

assign j_fu_297_p3 = ((and_ln10_reg_467[0:0] == 1'b1) ? add_ln12_fu_291_p2 : select_ln10_fu_275_p3);

assign k_fu_215_p2 = (k_mid2_fu_207_p3 + 3'd1);

assign k_mid2_fu_207_p3 = ((empty_4_fu_201_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k5_load);

assign prod_address0 = zext_ln16_1_fu_407_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = grp_fu_415_p3;

assign prod_we0 = prod_we0_local;

assign select_ln10_fu_275_p3 = ((icmp_ln127_reg_127[0:0] == 1'b1) ? 3'd0 : j4_fu_76);

assign select_ln12_1_fu_233_p3 = ((ap_phi_mux_icmp_ln127_phi_fu_131_p4[0:0] == 1'b1) ? 6'd1 : add_ln12_1_fu_227_p2);

assign tmp_1_fu_365_p3 = {{k_mid2_reg_477_pp0_iter2_reg}, {2'd0}};

assign tmp_fu_308_p3 = {{i_fu_283_p3}, {2'd0}};

assign xor_ln10_fu_189_p2 = (ap_phi_mux_icmp_ln127_phi_fu_131_p4 ^ 1'd1);

assign zext_ln12_fu_304_p1 = i_fu_283_p3;

assign zext_ln16_1_fu_407_p1 = add_ln16_1_reg_515_pp0_iter6_reg;

assign zext_ln16_2_fu_349_p1 = k_mid2_reg_477_pp0_iter2_reg;

assign zext_ln16_3_fu_352_p1 = k_mid2_reg_477_pp0_iter2_reg;

assign zext_ln16_4_fu_360_p1 = add_ln16_2_fu_355_p2;

assign zext_ln16_5_fu_384_p1 = add_ln16_3_fu_378_p2;

assign zext_ln16_fu_341_p1 = j_reg_499;

endmodule //matrix_mult
