// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.417000,HLS_SYN_LAT=83,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=309,HLS_SYN_LUT=568,HLS_VERSION=2024_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] a_address1;
output   a_ce1;
input  [7:0] a_q1;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] b_address1;
output   b_ce1;
input  [7:0] b_q1;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
wire   [0:0] icmp_ln10_fu_379_p2;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [7:0] reg_202;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg  signed [7:0] reg_207;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] reg_211;
reg   [2:0] i2_load_reg_524;
wire   [2:0] add_ln10_fu_233_p2;
reg   [2:0] add_ln10_reg_529;
wire   [2:0] select_ln10_fu_242_p3;
reg   [2:0] select_ln10_reg_534;
wire   [4:0] empty_4_fu_283_p1;
reg   [4:0] empty_4_reg_541;
wire   [4:0] zext_ln16_fu_287_p1;
reg   [4:0] zext_ln16_reg_555;
reg   [4:0] indvar_flatten1_load_reg_571;
wire   [4:0] empty_5_fu_321_p2;
reg   [4:0] empty_5_reg_576;
wire   [4:0] empty_6_fu_326_p2;
reg   [4:0] empty_6_reg_581;
wire   [4:0] add_ln16_8_fu_375_p2;
reg   [4:0] add_ln16_8_reg_606;
reg   [4:0] add_ln16_8_reg_606_pp0_iter1_reg;
reg   [4:0] add_ln16_8_reg_606_pp0_iter2_reg;
reg  signed [7:0] b_load_3_reg_611;
reg   [0:0] icmp_ln10_reg_616;
reg   [0:0] icmp_ln10_reg_616_pp0_iter1_reg;
reg   [0:0] icmp_ln10_reg_616_pp0_iter2_reg;
reg  signed [7:0] b_load_2_reg_640;
wire   [0:0] icmp_ln12_fu_410_p2;
reg   [0:0] icmp_ln12_reg_650;
wire   [15:0] mul_ln16_fu_436_p2;
reg  signed [15:0] mul_ln16_reg_665;
wire   [15:0] mul_ln16_4_fu_467_p2;
reg  signed [15:0] mul_ln16_4_reg_680;
wire  signed [15:0] grp_fu_481_p3;
reg   [15:0] add_ln16_1_reg_685;
wire  signed [15:0] grp_fu_488_p3;
reg  signed [15:0] add_ln16_reg_690;
(* use_dsp48 = "no" *) wire   [15:0] add_ln16_3_fu_473_p2;
reg   [15:0] add_ln16_3_reg_695;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_icmp_ln124_phi_fu_194_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage1;
wire   [63:0] p_cast6_fu_278_p1;
wire   [63:0] zext_ln16_4_fu_297_p1;
wire   [63:0] zext_ln16_5_fu_308_p1;
wire   [63:0] p_cast9_fu_336_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] p_cast10_fu_346_p1;
wire   [63:0] zext_ln16_2_fu_360_p1;
wire   [63:0] zext_ln16_3_fu_370_p1;
wire   [63:0] p_cast7_fu_385_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast8_fu_389_p1;
wire   [63:0] zext_ln12_fu_397_p1;
wire   [63:0] zext_ln16_6_fu_477_p1;
reg   [4:0] indvar_flatten1_fu_68;
wire   [4:0] add_ln10_1_fu_442_p2;
reg   [2:0] i2_fu_72;
wire   [2:0] i_fu_250_p3;
reg   [2:0] ap_sig_allocacmp_i2_load;
reg   [2:0] j3_fu_76;
wire   [2:0] j_fu_405_p2;
reg    a_ce0_local;
reg   [4:0] a_address0_local;
reg    a_ce1_local;
reg   [4:0] a_address1_local;
reg    b_ce1_local;
reg   [4:0] b_address1_local;
reg    b_ce0_local;
reg   [4:0] b_address0_local;
reg    prod_we0_local;
reg    prod_ce0_local;
wire   [4:0] tmp_fu_260_p3;
wire   [5:0] p_shl_fu_268_p1;
wire   [5:0] select_ln10_1_cast_fu_256_p1;
wire   [5:0] empty_fu_272_p2;
wire   [4:0] add_ln16_6_fu_291_p2;
wire   [4:0] add_ln16_7_fu_302_p2;
wire   [4:0] empty_7_fu_331_p2;
wire   [4:0] empty_8_fu_341_p2;
wire   [3:0] zext_ln16_1_fu_351_p1;
wire   [3:0] add_ln16_4_fu_354_p2;
wire   [4:0] add_ln16_5_fu_365_p2;
wire  signed [15:0] add_ln16_3_fu_473_p0;
wire   [15:0] grp_fu_495_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_523;
reg    ap_condition_529;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_68 = 5'd0;
#0 i2_fu_72 = 3'd0;
#0 j3_fu_76 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1(
    .din0(b_load_3_reg_611),
    .din1(reg_211),
    .dout(mul_ln16_fu_436_p2)
);

matrix_mult_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U2(
    .din0(reg_207),
    .din1(reg_202),
    .dout(mul_ln16_4_fu_467_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_207),
    .din1(a_q1),
    .din2(mul_ln16_reg_665),
    .ce(1'b1),
    .dout(grp_fu_481_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(reg_202),
    .din2(mul_ln16_4_reg_680),
    .ce(1'b1),
    .dout(grp_fu_488_p3)
);

matrix_mult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_load_2_reg_640),
    .din1(reg_211),
    .din2(add_ln16_1_reg_685),
    .ce(1'b1),
    .dout(grp_fu_495_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0)))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_529)) begin
            i2_fu_72 <= 3'd0;
        end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            i2_fu_72 <= i_fu_250_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten1_fu_68 <= 5'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten1_fu_68 <= add_ln10_1_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            j3_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j3_fu_76 <= j_fu_405_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_202 <= a_q1;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_202 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln10_reg_529 <= add_ln10_fu_233_p2;
        i2_load_reg_524 <= ap_sig_allocacmp_i2_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_1_reg_685 <= grp_fu_481_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln16_3_reg_695 <= add_ln16_3_fu_473_p2;
        add_ln16_8_reg_606 <= add_ln16_8_fu_375_p2;
        add_ln16_8_reg_606_pp0_iter1_reg <= add_ln16_8_reg_606;
        add_ln16_8_reg_606_pp0_iter2_reg <= add_ln16_8_reg_606_pp0_iter1_reg;
        empty_5_reg_576 <= empty_5_fu_321_p2;
        empty_6_reg_581 <= empty_6_fu_326_p2;
        icmp_ln10_reg_616 <= icmp_ln10_fu_379_p2;
        icmp_ln10_reg_616_pp0_iter1_reg <= icmp_ln10_reg_616;
        icmp_ln10_reg_616_pp0_iter2_reg <= icmp_ln10_reg_616_pp0_iter1_reg;
        indvar_flatten1_load_reg_571 <= indvar_flatten1_fu_68;
        mul_ln16_4_reg_680 <= mul_ln16_4_fu_467_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_reg_690 <= grp_fu_488_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_load_2_reg_640 <= b_q1;
        icmp_ln12_reg_650 <= icmp_ln12_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_load_3_reg_611 <= b_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_4_reg_541 <= empty_4_fu_283_p1;
        mul_ln16_reg_665 <= mul_ln16_fu_436_p2;
        select_ln10_reg_534 <= select_ln10_fu_242_p3;
        zext_ln16_reg_555[2 : 0] <= zext_ln16_fu_287_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_207 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_211 <= a_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0_local = p_cast8_fu_389_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0_local = p_cast9_fu_336_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address0_local = p_cast6_fu_278_p1;
    end else begin
        a_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address1_local = p_cast7_fu_385_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address1_local = p_cast10_fu_346_p1;
    end else begin
        a_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_379_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10_reg_616_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        if ((1'b1 == ap_condition_523)) begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_650;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_650;
        end
    end else begin
        ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_650;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i2_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address0_local = zext_ln12_fu_397_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0_local = zext_ln16_2_fu_360_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0_local = zext_ln16_5_fu_308_p1;
    end else begin
        b_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            b_address1_local = zext_ln16_3_fu_370_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            b_address1_local = zext_ln16_4_fu_297_p1;
        end else begin
            b_address1_local = 'bx;
        end
    end else begin
        b_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        b_ce1_local = 1'b1;
    end else begin
        b_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = a_address0_local;

assign a_address1 = a_address1_local;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign add_ln10_1_fu_442_p2 = (indvar_flatten1_load_reg_571 + 5'd1);

assign add_ln10_fu_233_p2 = (ap_sig_allocacmp_i2_load + 3'd1);

assign add_ln16_3_fu_473_p0 = grp_fu_495_p3;

assign add_ln16_3_fu_473_p2 = ($signed(add_ln16_3_fu_473_p0) + $signed(add_ln16_reg_690));

assign add_ln16_4_fu_354_p2 = (zext_ln16_1_fu_351_p1 + 4'd5);

assign add_ln16_5_fu_365_p2 = (zext_ln16_reg_555 + 5'd10);

assign add_ln16_6_fu_291_p2 = (zext_ln16_fu_287_p1 + 5'd15);

assign add_ln16_7_fu_302_p2 = ($signed(zext_ln16_fu_287_p1) + $signed(5'd20));

assign add_ln16_8_fu_375_p2 = (empty_4_reg_541 + zext_ln16_reg_555);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_523 = ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln10_reg_616 == 1'd0));
end

always @ (*) begin
    ap_condition_529 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign b_address0 = b_address0_local;

assign b_address1 = b_address1_local;

assign b_ce0 = b_ce0_local;

assign b_ce1 = b_ce1_local;

assign empty_4_fu_283_p1 = empty_fu_272_p2[4:0];

assign empty_5_fu_321_p2 = (empty_4_reg_541 + 5'd1);

assign empty_6_fu_326_p2 = (empty_4_reg_541 + 5'd2);

assign empty_7_fu_331_p2 = (empty_4_reg_541 + 5'd3);

assign empty_8_fu_341_p2 = (empty_4_reg_541 + 5'd4);

assign empty_fu_272_p2 = (p_shl_fu_268_p1 + select_ln10_1_cast_fu_256_p1);

assign i_fu_250_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_194_p4[0:0] == 1'b1) ? add_ln10_reg_529 : i2_load_reg_524);

assign icmp_ln10_fu_379_p2 = ((indvar_flatten1_fu_68 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_410_p2 = ((j_fu_405_p2 == 3'd5) ? 1'b1 : 1'b0);

assign j_fu_405_p2 = (select_ln10_reg_534 + 3'd1);

assign p_cast10_fu_346_p1 = empty_8_fu_341_p2;

assign p_cast6_fu_278_p1 = empty_fu_272_p2;

assign p_cast7_fu_385_p1 = empty_5_reg_576;

assign p_cast8_fu_389_p1 = empty_6_reg_581;

assign p_cast9_fu_336_p1 = empty_7_fu_331_p2;

assign p_shl_fu_268_p1 = tmp_fu_260_p3;

assign prod_address0 = zext_ln16_6_fu_477_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = add_ln16_3_reg_695;

assign prod_we0 = prod_we0_local;

assign select_ln10_1_cast_fu_256_p1 = i_fu_250_p3;

assign select_ln10_fu_242_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_194_p4[0:0] == 1'b1) ? 3'd0 : j3_fu_76);

assign tmp_fu_260_p3 = {{i_fu_250_p3}, {2'd0}};

assign zext_ln12_fu_397_p1 = select_ln10_reg_534;

assign zext_ln16_1_fu_351_p1 = select_ln10_reg_534;

assign zext_ln16_2_fu_360_p1 = add_ln16_4_fu_354_p2;

assign zext_ln16_3_fu_370_p1 = add_ln16_5_fu_365_p2;

assign zext_ln16_4_fu_297_p1 = add_ln16_6_fu_291_p2;

assign zext_ln16_5_fu_308_p1 = add_ln16_7_fu_302_p2;

assign zext_ln16_6_fu_477_p1 = add_ln16_8_reg_606_pp0_iter2_reg;

assign zext_ln16_fu_287_p1 = select_ln10_fu_242_p3;

always @ (posedge ap_clk) begin
    zext_ln16_reg_555[4:3] <= 2'b00;
end

endmodule //matrix_mult
