// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.396000,HLS_SYN_LAT=34,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=332,HLS_SYN_LUT=323,HLS_VERSION=2024_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] a_address0;
output   a_ce0;
input  [39:0] a_q0;
output  [2:0] b_address0;
output   b_ce0;
input  [39:0] b_q0;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_loop_exit_ready_delayed;
reg   [0:0] icmp_ln10_reg_439;
reg   [0:0] icmp_ln10_reg_439_pp0_iter1_reg;
wire   [2:0] select_ln10_fu_181_p3;
reg   [2:0] select_ln10_reg_443;
wire   [2:0] i_fu_189_p3;
reg   [2:0] i_reg_448;
wire   [0:0] icmp_ln12_fu_213_p2;
reg   [0:0] icmp_ln12_reg_464;
reg  signed [7:0] tmp5_reg_474;
reg   [7:0] tmp_s_reg_479;
reg  signed [7:0] tmp_s_reg_479_pp0_iter3_reg;
reg  signed [7:0] tmp_1_reg_484;
wire   [4:0] add_ln16_4_fu_300_p2;
reg   [4:0] add_ln16_4_reg_494;
reg   [4:0] add_ln16_4_reg_494_pp0_iter3_reg;
reg   [4:0] add_ln16_4_reg_494_pp0_iter4_reg;
reg   [4:0] add_ln16_4_reg_494_pp0_iter5_reg;
reg   [4:0] add_ln16_4_reg_494_pp0_iter6_reg;
reg   [4:0] add_ln16_4_reg_494_pp0_iter7_reg;
reg  signed [7:0] tmp_3_reg_504;
reg   [7:0] tmp_4_reg_509;
reg  signed [7:0] tmp_4_reg_509_pp0_iter3_reg;
reg  signed [7:0] tmp_5_reg_514;
wire   [15:0] mul_ln16_2_fu_370_p2;
reg  signed [15:0] mul_ln16_2_reg_524;
wire   [15:0] mul_ln16_4_fu_376_p2;
reg  signed [15:0] mul_ln16_4_reg_529;
wire  signed [15:0] grp_fu_403_p3;
reg  signed [15:0] add_ln16_reg_544;
reg  signed [15:0] add_ln16_reg_544_pp0_iter6_reg;
wire  signed [15:0] grp_fu_396_p3;
reg   [15:0] add_ln16_1_reg_549;
(* use_dsp48 = "no" *) wire   [15:0] add_ln16_3_fu_388_p2;
reg   [15:0] add_ln16_3_reg_554;
reg   [0:0] ap_phi_mux_icmp_ln124_phi_fu_127_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln10_fu_197_p1;
wire   [63:0] zext_ln12_fu_202_p1;
wire   [63:0] zext_ln16_1_fu_392_p1;
reg   [4:0] indvar_flatten1_fu_72;
wire   [4:0] add_ln10_1_fu_152_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [2:0] i2_fu_76;
reg   [2:0] j3_fu_80;
wire   [2:0] j_fu_207_p2;
reg    a_ce0_local;
reg    b_ce0_local;
reg    prod_we0_local;
reg    prod_ce0_local;
wire   [2:0] add_ln10_fu_175_p2;
wire   [4:0] tmp_fu_232_p3;
wire   [4:0] select_ln10_1_cast_fu_229_p1;
wire  signed [7:0] empty_fu_245_p1;
wire  signed [7:0] tmp_2_fu_283_p4;
wire   [4:0] mul_ln16_5_fu_239_p2;
wire   [4:0] zext_ln16_fu_297_p1;
wire  signed [7:0] trunc_ln16_fu_306_p1;
wire  signed [7:0] tmp_6_fu_344_p4;
wire  signed [15:0] add_ln16_3_fu_388_p0;
wire   [15:0] grp_fu_410_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_196;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 indvar_flatten1_fu_72 = 5'd0;
#0 i2_fu_76 = 3'd0;
#0 j3_fu_80 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1(
    .din0(tmp_5_reg_514),
    .din1(tmp_1_reg_484),
    .dout(mul_ln16_2_fu_370_p2)
);

matrix_mult_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U2(
    .din0(tmp_3_reg_504),
    .din1(tmp5_reg_474),
    .dout(mul_ln16_4_fu_376_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_6_fu_344_p4),
    .din1(tmp_2_fu_283_p4),
    .din2(mul_ln16_2_reg_524),
    .ce(1'b1),
    .dout(grp_fu_396_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln16_fu_306_p1),
    .din1(empty_fu_245_p1),
    .din2(mul_ln16_4_reg_529),
    .ce(1'b1),
    .dout(grp_fu_403_p3)
);

matrix_mult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_509_pp0_iter3_reg),
    .din1(tmp_s_reg_479_pp0_iter3_reg),
    .din2(add_ln16_1_reg_549),
    .ce(1'b1),
    .dout(grp_fu_410_p3)
);

matrix_mult_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            i2_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i2_fu_76 <= i_fu_189_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_196)) begin
        indvar_flatten1_fu_72 <= add_ln10_1_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
        j3_fu_80 <= 3'd0;
    end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        j3_fu_80 <= j_fu_207_p2;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        add_ln16_1_reg_549 <= grp_fu_396_p3;
        add_ln16_reg_544 <= grp_fu_403_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln16_3_reg_554 <= add_ln16_3_fu_388_p2;
        add_ln16_4_reg_494 <= add_ln16_4_fu_300_p2;
        add_ln16_4_reg_494_pp0_iter3_reg <= add_ln16_4_reg_494;
        add_ln16_4_reg_494_pp0_iter4_reg <= add_ln16_4_reg_494_pp0_iter3_reg;
        add_ln16_4_reg_494_pp0_iter5_reg <= add_ln16_4_reg_494_pp0_iter4_reg;
        add_ln16_4_reg_494_pp0_iter6_reg <= add_ln16_4_reg_494_pp0_iter5_reg;
        add_ln16_4_reg_494_pp0_iter7_reg <= add_ln16_4_reg_494_pp0_iter6_reg;
        add_ln16_reg_544_pp0_iter6_reg <= add_ln16_reg_544;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        mul_ln16_2_reg_524 <= mul_ln16_2_fu_370_p2;
        mul_ln16_4_reg_529 <= mul_ln16_4_fu_376_p2;
        tmp5_reg_474 <= {{a_q0[15:8]}};
        tmp_1_reg_484 <= {{a_q0[31:24]}};
        tmp_3_reg_504 <= {{b_q0[15:8]}};
        tmp_4_reg_509 <= {{b_q0[23:16]}};
        tmp_4_reg_509_pp0_iter3_reg <= tmp_4_reg_509;
        tmp_5_reg_514 <= {{b_q0[31:24]}};
        tmp_s_reg_479 <= {{a_q0[23:16]}};
        tmp_s_reg_479_pp0_iter3_reg <= tmp_s_reg_479;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        i_reg_448 <= i_fu_189_p3;
        icmp_ln10_reg_439 <= icmp_ln10_fu_158_p2;
        icmp_ln10_reg_439_pp0_iter1_reg <= icmp_ln10_reg_439;
        select_ln10_reg_443 <= select_ln10_fu_181_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln12_reg_464 <= icmp_ln12_fu_213_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_439_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_icmp_ln124_phi_fu_127_p4 = icmp_ln12_reg_464;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln124_phi_fu_127_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln124_phi_fu_127_p4 = icmp_ln12_reg_464;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln10_fu_197_p1;

assign a_ce0 = a_ce0_local;

assign add_ln10_1_fu_152_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 5'd1);

assign add_ln10_fu_175_p2 = (i2_fu_76 + 3'd1);

assign add_ln16_3_fu_388_p0 = grp_fu_410_p3;

assign add_ln16_3_fu_388_p2 = ($signed(add_ln16_3_fu_388_p0) + $signed(add_ln16_reg_544_pp0_iter6_reg));

assign add_ln16_4_fu_300_p2 = (mul_ln16_5_fu_239_p2 + zext_ln16_fu_297_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_196 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_address0 = zext_ln12_fu_202_p1;

assign b_ce0 = b_ce0_local;

assign empty_fu_245_p1 = a_q0[7:0];

assign i_fu_189_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_127_p4[0:0] == 1'b1) ? add_ln10_fu_175_p2 : i2_fu_76);

assign icmp_ln10_fu_158_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_213_p2 = ((j_fu_207_p2 == 3'd5) ? 1'b1 : 1'b0);

assign j_fu_207_p2 = (select_ln10_fu_181_p3 + 3'd1);

assign mul_ln16_5_fu_239_p2 = (tmp_fu_232_p3 + select_ln10_1_cast_fu_229_p1);

assign prod_address0 = zext_ln16_1_fu_392_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = add_ln16_3_reg_554;

assign prod_we0 = prod_we0_local;

assign select_ln10_1_cast_fu_229_p1 = i_reg_448;

assign select_ln10_fu_181_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_127_p4[0:0] == 1'b1) ? 3'd0 : j3_fu_80);

assign tmp_2_fu_283_p4 = {{a_q0[39:32]}};

assign tmp_6_fu_344_p4 = {{b_q0[39:32]}};

assign tmp_fu_232_p3 = {{i_reg_448}, {2'd0}};

assign trunc_ln16_fu_306_p1 = b_q0[7:0];

assign zext_ln10_fu_197_p1 = i_fu_189_p3;

assign zext_ln12_fu_202_p1 = select_ln10_fu_181_p3;

assign zext_ln16_1_fu_392_p1 = add_ln16_4_reg_494_pp0_iter7_reg;

assign zext_ln16_fu_297_p1 = select_ln10_reg_443;

endmodule //matrix_mult
